using System.Collections.Generic;

namespace BarcodeBakery.Common.GS1
{
    /// <summary>
    /// GS1 AI Data.
    /// </summary>
    public class GS1AI
    {
        /// <summary>
        /// Gets the default AI Data.
        /// </summary>
        /// <returns>AI Data.</returns>
        public static IEnumerable<AIData> GetDefaultAIData()
        {
            return new AIData[]
            {
                new AIData("00", KindOfData.Numeric, 18, 18, true),
                new AIData("01", KindOfData.Numeric, 14, 14, true),
                new AIData("02", KindOfData.Numeric, 14, 14, true),
                new AIData("10", KindOfData.Alphanumeric, 1,  20, false),
                new AIData("11", KindOfData.Date, 6, 6, false),
                new AIData("12", KindOfData.Date, 6, 6, false),
                new AIData("13", KindOfData.Date, 6, 6, false),
                new AIData("15", KindOfData.Date, 6, 6, false),
                new AIData("16", KindOfData.Date, 6, 6, false),
                new AIData("17", KindOfData.Date, 6, 6, false),
                new AIData("20", KindOfData.Numeric, 2, 2, false),
                new AIData("21", KindOfData.Alphanumeric, 1, 20, false),
                new AIData("22", KindOfData.Alphanumeric, 1, 20, false),
                new AIData("235", KindOfData.Alphanumeric, 1, 28, false),
                new AIData("240", KindOfData.Alphanumeric, 1, 30, false),
                new AIData("241", KindOfData.Alphanumeric, 1, 30, false),
                new AIData("242", KindOfData.Alphanumeric, 1, 6, false),
                new AIData("243", KindOfData.Alphanumeric, 1, 20, false),
                new AIData("250", KindOfData.Alphanumeric, 1, 30, false),
                new AIData("251", KindOfData.Alphanumeric, 1, 30, false),
                new AIData("253", KindOfData.Numeric, 14, 30, false),
                new AIData("254", KindOfData.Numeric, 1, 20, false),
                new AIData("255", KindOfData.Numeric, 14, 25, false),
                new AIData("30", KindOfData.Numeric, 1,  8, false),
                new AIData("310y", KindOfData.Numeric, 6, 6, false),
                new AIData("311y", KindOfData.Numeric, 6, 6, false),
                new AIData("312y", KindOfData.Numeric, 6, 6, false),
                new AIData("313y", KindOfData.Numeric, 6, 6, false),
                new AIData("314y", KindOfData.Numeric, 6, 6, false),
                new AIData("315y", KindOfData.Numeric, 6, 6, false),
                new AIData("316y", KindOfData.Numeric, 6, 6, false),
                new AIData("320y", KindOfData.Numeric, 6, 6, false),
                new AIData("321y", KindOfData.Numeric, 6, 6, false),
                new AIData("322y", KindOfData.Numeric, 6, 6, false),
                new AIData("323y", KindOfData.Numeric, 6, 6, false),
                new AIData("324y", KindOfData.Numeric, 6, 6, false),
                new AIData("325y", KindOfData.Numeric, 6, 6, false),
                new AIData("326y", KindOfData.Numeric, 6, 6, false),
                new AIData("327y", KindOfData.Numeric, 6, 6, false),
                new AIData("328y", KindOfData.Numeric, 6, 6, false),
                new AIData("329y", KindOfData.Numeric, 6, 6, false),
                new AIData("330y", KindOfData.Numeric, 6, 6, false),
                new AIData("331y", KindOfData.Numeric, 6, 6, false),
                new AIData("332y", KindOfData.Numeric, 6, 6, false),
                new AIData("333y", KindOfData.Numeric, 6, 6, false),
                new AIData("334y", KindOfData.Numeric, 6, 6, false),
                new AIData("335y", KindOfData.Numeric, 6, 6, false),
                new AIData("336y", KindOfData.Numeric, 6, 6, false),
                new AIData("337y", KindOfData.Numeric, 6, 6, false),
                new AIData("340y", KindOfData.Numeric, 6, 6, false),
                new AIData("341y", KindOfData.Numeric, 6, 6, false),
                new AIData("342y", KindOfData.Numeric, 6, 6, false),
                new AIData("343y", KindOfData.Numeric, 6, 6, false),
                new AIData("344y", KindOfData.Numeric, 6, 6, false),
                new AIData("345y", KindOfData.Numeric, 6, 6, false),
                new AIData("346y", KindOfData.Numeric, 6, 6, false),
                new AIData("347y", KindOfData.Numeric, 6, 6, false),
                new AIData("348y", KindOfData.Numeric, 6, 6, false),
                new AIData("349y", KindOfData.Numeric, 6, 6, false),
                new AIData("350y", KindOfData.Numeric, 6, 6, false),
                new AIData("351y", KindOfData.Numeric, 6, 6, false),
                new AIData("352y", KindOfData.Numeric, 6, 6, false),
                new AIData("353y", KindOfData.Numeric, 6, 6, false),
                new AIData("354y", KindOfData.Numeric, 6, 6, false),
                new AIData("355y", KindOfData.Numeric, 6, 6, false),
                new AIData("356y", KindOfData.Numeric, 6, 6, false),
                new AIData("357y", KindOfData.Numeric, 6, 6, false),
                new AIData("360y", KindOfData.Numeric, 6, 6, false),
                new AIData("361y", KindOfData.Numeric, 6, 6, false),
                new AIData("362y", KindOfData.Numeric, 6, 6, false),
                new AIData("363y", KindOfData.Numeric, 6, 6, false),
                new AIData("364y", KindOfData.Numeric, 6, 6, false),
                new AIData("365y", KindOfData.Numeric, 6, 6, false),
                new AIData("366y", KindOfData.Numeric, 6, 6, false),
                new AIData("367y", KindOfData.Numeric, 6, 6, false),
                new AIData("368y", KindOfData.Numeric, 6, 6, false),
                new AIData("369y", KindOfData.Numeric, 6, 6, false),
                new AIData("37", KindOfData.Numeric, 1, 8, false),
                new AIData("390y", KindOfData.Numeric, 1, 15, false),
                new AIData("391y", KindOfData.Numeric, 4, 18, false),
                new AIData("392y", KindOfData.Numeric, 1, 15, false),
                new AIData("393y", KindOfData.Numeric, 4, 18, false),
                new AIData("394y", KindOfData.Numeric, 4, 4, false),
                new AIData("395y", KindOfData.Numeric, 6, 6, false),
                new AIData("400", KindOfData.Alphanumeric, 1, 30, false),
                new AIData("401", KindOfData.Alphanumeric, 1, 30, false),
                new AIData("402", KindOfData.Numeric, 17, 17, false),
                new AIData("403", KindOfData.Alphanumeric, 1, 30, false),
                new AIData("410", KindOfData.Numeric, 13, 13, true),
                new AIData("411", KindOfData.Numeric, 13, 13, true),
                new AIData("412", KindOfData.Numeric, 13, 13, true),
                new AIData("413", KindOfData.Numeric, 13, 13, true),
                new AIData("414", KindOfData.Numeric, 13, 13, true),
                new AIData("415", KindOfData.Numeric, 13, 13, true),
                new AIData("416", KindOfData.Numeric, 13, 13, true),
                new AIData("417", KindOfData.Numeric, 13, 13, true),
                new AIData("420", KindOfData.Alphanumeric, 1, 20, false),
                new AIData("421", KindOfData.Alphanumeric, 4, 12, false),
                new AIData("422", KindOfData.Numeric, 3, 3, false),
                new AIData("423", KindOfData.Numeric, 3, 15, false),
                new AIData("424", KindOfData.Numeric, 3, 3, false),
                new AIData("425", KindOfData.Numeric, 3, 3, false),
                new AIData("426", KindOfData.Numeric, 3, 3, false),
                new AIData("427", KindOfData.Alphanumeric, 1, 3, false),
                new AIData("4300", KindOfData.Alphanumeric, 1, 35, false),
                new AIData("4301", KindOfData.Alphanumeric, 1, 35, false),
                new AIData("4302", KindOfData.Alphanumeric, 1, 70, false),
                new AIData("4303", KindOfData.Alphanumeric, 1, 70, false),
                new AIData("4304", KindOfData.Alphanumeric, 1, 70, false),
                new AIData("4305", KindOfData.Alphanumeric, 1, 70, false),
                new AIData("4306", KindOfData.Alphanumeric, 1, 70, false),
                new AIData("4307", KindOfData.Alphanumeric, 2, 2, false),
                new AIData("4308", KindOfData.Alphanumeric, 1, 30, false),
                new AIData("4310", KindOfData.Alphanumeric, 1, 35, false),
                new AIData("4311", KindOfData.Alphanumeric, 1, 35, false),
                new AIData("4312", KindOfData.Alphanumeric, 1, 70, false),
                new AIData("4313", KindOfData.Alphanumeric, 1, 70, false),
                new AIData("4314", KindOfData.Alphanumeric, 1, 70, false),
                new AIData("4315", KindOfData.Alphanumeric, 1, 70, false),
                new AIData("4316", KindOfData.Alphanumeric, 1, 70, false),
                new AIData("4317", KindOfData.Alphanumeric, 2, 2, false),
                new AIData("4318", KindOfData.Alphanumeric, 1, 20, false),
                new AIData("4319", KindOfData.Alphanumeric, 1, 30, false),
                new AIData("4320", KindOfData.Alphanumeric, 1, 35, false),
                new AIData("4321", KindOfData.Numeric, 1, 1, false),
                new AIData("4322", KindOfData.Numeric, 1, 1, false),
                new AIData("4323", KindOfData.Numeric, 1, 1, false),
                new AIData("4324", KindOfData.DateTime, 10, 10, false),
                new AIData("4325", KindOfData.DateTime, 10, 10, false),
                new AIData("4326", KindOfData.Date, 6, 6, false),
                new AIData("7001", KindOfData.Numeric, 13, 13, false),
                new AIData("7002", KindOfData.Alphanumeric, 1, 30, false),
                new AIData("7003", KindOfData.DateTime, 10, 10, false),
                new AIData("7004", KindOfData.Numeric, 1, 4, false),
                new AIData("7005", KindOfData.Alphanumeric, 1, 12, false),
                new AIData("7006", KindOfData.Date, 6, 6, false),
                new AIData("7007", KindOfData.Numeric, 6, 12, false),
                new AIData("7008", KindOfData.Alphanumeric, 1, 3, false),
                new AIData("7009", KindOfData.Alphanumeric, 1, 10, false),
                new AIData("7010", KindOfData.Alphanumeric, 1, 2, false),
                new AIData("7020", KindOfData.Alphanumeric, 1, 20, false),
                new AIData("7021", KindOfData.Alphanumeric, 1, 20, false),
                new AIData("7022", KindOfData.Alphanumeric, 1, 20, false),
                new AIData("7023", KindOfData.Alphanumeric, 1, 30, false),
                new AIData("703y", KindOfData.Alphanumeric, 3, 30, false),
                new AIData("7040", KindOfData.Alphanumeric, 4, 4, false),
                new AIData("710", KindOfData.Alphanumeric, 1, 20, false),
                new AIData("711", KindOfData.Alphanumeric, 1, 20, false),
                new AIData("712", KindOfData.Alphanumeric, 1, 20, false),
                new AIData("713", KindOfData.Alphanumeric, 1, 20, false),
                new AIData("714", KindOfData.Alphanumeric, 1, 20, false),
                new AIData("723y", KindOfData.Alphanumeric, 2,30, false),
                new AIData("7240", KindOfData.Alphanumeric, 1, 20, false),
                new AIData("8001", KindOfData.Numeric, 14, 14, false),
                new AIData("8002", KindOfData.Alphanumeric, 1, 20, false),
                new AIData("8003", KindOfData.Alphanumeric, 15, 30, false),
                new AIData("8004", KindOfData.Alphanumeric, 1, 30, false),
                new AIData("8005", KindOfData.Numeric, 6, 6, false),
                new AIData("8006", KindOfData.Numeric, 18, 18, false),
                new AIData("8007", KindOfData.Alphanumeric, 1, 34, false),
                new AIData("8008", KindOfData.DateTime, 8, 12, false),
                new AIData("8009", KindOfData.Alphanumeric, 1, 50, false),
                new AIData("8010", KindOfData.Alphanumeric, 1, 30, false),
                new AIData("8011", KindOfData.Numeric, 1, 12, false),
                new AIData("8012", KindOfData.Alphanumeric, 1, 20, false),
                new AIData("8013", KindOfData.Alphanumeric, 1, 30, false),
                new AIData("8017", KindOfData.Numeric, 18, 18, false),
                new AIData("8018", KindOfData.Numeric, 18, 18, false),
                new AIData("8019", KindOfData.Numeric, 1,  10, false),
                new AIData("8020", KindOfData.Alphanumeric, 1, 25, false),
                new AIData("8026", KindOfData.Numeric, 18, 18, false),
                new AIData("8110", KindOfData.Alphanumeric, 1, 70, false),
                new AIData("8111", KindOfData.Numeric, 4, 4, false),
                new AIData("8112", KindOfData.Alphanumeric, 1, 70, false),
                new AIData("8200", KindOfData.Alphanumeric, 1, 70, false),
                new AIData("90", KindOfData.Alphanumeric, 1, 30, false),
                new AIData("91", KindOfData.Alphanumeric, 1, 90, false),
                new AIData("92", KindOfData.Alphanumeric, 1, 90, false),
                new AIData("93", KindOfData.Alphanumeric, 1, 90, false),
                new AIData("94", KindOfData.Alphanumeric, 1, 90, false),
                new AIData("95", KindOfData.Alphanumeric, 1, 90, false),
                new AIData("96", KindOfData.Alphanumeric, 1, 90, false),
                new AIData("97", KindOfData.Alphanumeric, 1, 90, false),
                new AIData("98", KindOfData.Alphanumeric, 1, 90, false),
                new AIData("99", KindOfData.Alphanumeric, 1, 90, false)
            };
        }
    }
}
